### ISSUE TITLE
Fix: Autoupdate errors

### ISSUE THREAD

**Issue by srishChicago** [BlueBubblesApp/bluebubbles-server#653]
Hi there, first off, thank you for developing such a great program! I've really enjoyed using BlueBubbles for a few months now.

I'm no developer, but thought I'd share this that keeps popping up regularly as I run the server in terminal mode:

``[2024-06-11 10:19:46.706][debug] Error: Cannot find latest-mac.yml in the latest release artifacts (https://github.com/BlueBubblesApp/bluebubbles-server/releases/download/v1.9.7/latest-mac.yml): HttpError: 404 
"method: GET url: https://github.com/BlueBubblesApp/bluebubbles-server/releases/download/v1.9.7/latest-mac.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Tue, 11 Jun 2024 15:19:31 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "CAAE:20A0FC:3A3D3B9:52446A4:66686B12"
}
    at createHttpError (/Applications/BlueBubbles.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:14:12)
    at ElectronHttpExecutor.handleResponse (/Applications/BlueBubbles.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:116:20)
    at ClientRequest.<anonymous> (/Applications/BlueBubbles.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:82:26)
    at ClientRequest.emit (node:events:390:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:6816)
    at SimpleURLLoaderWrapper.emit (node:events:390:28)
    at Object.newError (/Applications/BlueBubbles.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/index.js:47:19)
    at fetchData (/Applications/BlueBubbles.app/Contents/Resources/app.asar/node_modules/electron-updater/out/providers/GitHubProvider.js:108:50)
    at async GitHubProvider.getLatestVersion (/Applications/BlueBubbles.app/Contents/Resources/app.asar/node_modules/electron-updater/out/providers/GitHubProvider.js:115:23)
    at async MacUpdater.getUpdateInfoAndProvider (/Applications/BlueBubbles.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:319:19)
    at async MacUpdater.doCheckForUpdates (/Applications/BlueBubbles.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:333:24)
    at async rl.checkForUpdate (/Applications/BlueBubbles.app/Contents/Resources/app.asar/dist/main.js:1:97017)
    at async Function.checkForUpdate (/Applications/BlueBubbles.app/Contents/Resources/app.asar/dist/main.js:1:214060)
    at async checkForUpdate (/Applications/BlueBubbles.app/Contents/Resources/app.asar/dist/main.js:1:278348)
    at async /Applications/BlueBubbles.app/Contents/Resources/app.asar/dist/main.js:1:300531
    at async Th (/Applications/BlueBubbles.app/Contents/Resources/app.asar/dist/main.js:1:248509)

**Comment by zlshames** [comment]
This is known. It's due to the fact that Apple revoked my Apple Developer Certificates. As a result, it broke our auto-update system, causing this to error out.

**Comment by zlshames** [comment]
fixed, `development branch`. closing

**Comment by qayshp** [comment]
I think it might be worth including a `latest-mac.yml` in newer releases.

Including a `latest-mac.yml` file in releases, while no longer relevant to current update system, would allow older versions to at least detect and attempt to update. The update would fail, but at least users would know that an update was available.

For example, I had `1.9.7` installed and would regularly run the update check in the app from the menu bar.
