### ISSUE TITLE
Unable to install dependencies for dev environment: node-mac-contacts

### ISSUE THREAD

**Issue by joshuafhiggins** [BlueBubblesApp/bluebubbles-server#686]
Hey I'm running into an issue trying to setup a dev environment that's failing at node-mac-contacts, I'm unsure if this is related or unrelated to the move away from Yarn. I do have python installed and have tried running `npm install` and `yarn`. This is what I get when it fails:

```
error /Users/joshuafhiggins/GitHub/BlueBubbles-Server/node_modules/node-mac-permissions: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/joshuafhiggins/GitHub/BlueBubbles-Server/node_modules/node-mac-permissions
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.1
gyp info using node@22.6.0 | darwin | arm64
(node:54997) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info find Python using Python version 3.12.5 found at "/Library/Frameworks/Python.framework/Versions/3.12/bin/python3"
gyp info spawn /Library/Frameworks/Python.framework/Versions/3.12/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/joshuafhiggins/GitHub/BlueBubbles-Server/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/joshuafhiggins/GitHub/BlueBubbles-Server/node_modules/node-mac-permissions/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/joshuafhiggins/GitHub/BlueBubbles-Server/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/joshuafhiggins/Library/Caches/node-gyp/22.6.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/joshuafhiggins/Library/Caches/node-gyp/22.6.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/joshuafhiggins/GitHub/BlueBubbles-Server/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/joshuafhiggins/Library/Caches/node-gyp/22.6.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/joshuafhiggins/GitHub/BlueBubbles-Server/node_modules/node-mac-permissions',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "/Users/joshuafhiggins/GitHub/BlueBubbles-Server/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
    import gyp  # noqa: E402
    ^^^^^^^^^^
  File "/Users/joshuafhiggins/GitHub/BlueBubbles-Server/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
    import gyp.input
  File "/Users/joshuafhiggins/GitHub/BlueBubbles-Server/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/joshuafhiggins/GitHub/BlueBubbles-Server/node_modules/node-gyp/lib/configure.js:325:16)
gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Darwin 24.0.0
gyp ERR! command "/opt/homebrew/Cellar/node/22.6.0/bin/node" "/Users/joshuafhiggins/GitHub/BlueBubbles-Server/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/joshuafhiggins/GitHub/BlueBubbles-Server/node_modules/node-mac-permissions
```

**Comment by zlshames** [comment]
Yeah for some reason, yarn doesn't work well with the project after we upgraded electron/NodeJS to a later version. Now we just need to use npm. So delete your yarn lock and what not. 

Also, after some research, distutils was removed from python in v3.12, which is what you're using. Consider downgrading I guess

**Comment by joshuafhiggins** [comment]
Got it! For others with the same problem, use Python 3.10.

Also there are other build problems I'm going to sort out on Sequoia with node-mac-contacts, I believe there was an API change in how contact permissions are asked for and received (at least there was on iOS but they usually also appear on macOS too)

**Comment by mpowney** [comment]
If anyone else has come across this thread because they encounter node-gyp errors during ```npm install``` - I followed the advice provided earlier, plus specifying the version of node. 

Assuming you have nvm to manage your versions of node, from the ```bluebubbles-server``` folder, the following should do the trick:
* ```brew install python@3.10```
* ```nvm install 20.11```
* ```nvm use 20.11``` (not necessary if nvm install swapped to 20.11 already)
* ```npm install --python=python3.10```

**Comment by zlshames** [comment]
> If anyone else has come across this thread because they encounter node-gyp errors during `npm install` - I followed the advice provided earlier, plus specifying the version of node.
> 
> Assuming you have nvm to manage your versions of node, from the `bluebubbles-server` folder, the following should do the trick:
> 
> * `brew install python@3.10`
> * `nvm install 20.11`
> * `nvm use 20.11` (not necessary if nvm install swapped to 20.11 already)
> * `npm install --python=python3.10`

are you using the `development` branch or `master`? if master, try the dev branch to see if that resolves anything.

**Comment by mpowney** [comment]
Swapped to the development branch, attempted ```npm install``` with latest version of node v22 e.g. ```nvm use 22```, received the error ```Invalid property "node"```

Verbose output below:

```
v22.22.0 is already installed.
Now using node v22.22.0 (npm v10.9.4)

yyy@xxx bluebubbles-server % npm i 
npm error Invalid property "node"
npm error A complete log of this run can be found in: /Users/yyy/.npm/_1ogs/2026-02-19T05_11_07_649Z-debug-0.1og 

yyy@xxx bluebubbles-server % cat /Users/yyy/.npm/_1ogs/2026-02-19T05_11_07_649Z-debug-0.1og
0 verbose cli /Users/yyy/.nvm/versions/node/v22.22.0/bin/node /Users/yyy/.nvm/versions/node/v22.22.0/bin/npm
1 info using npm@10.9.4
2 info using node@v22.22.0
3 silly config load:file:/Users/yyy/.nvm/versions/node/v22.22.0/lib/node_modules/npm/npmrc
4 silly config load:file:/Users/yyy/Documents/Code/git/bluebubbles-server/.npmrc
5 silly config load:file:/Users/yyy/.npmrc
6 silly config load:file:/Users/yyy/.nvm/versions/node/v22.22.0/etc/npmrc
7 verbose title npm i
8 verbose argv "1"
9 verbose logfile logs-max:10 dir:/Users/yyy/.npm/_1ogs/2026-02-19T05_11_07_649Z-
10 verbose logfile/Users/yyy/.npm/_1ogs/2026-02-19T05_11_07_649Z-debug-0.1og
11 silly logfile done cleaning log files
12 verbose stack Error: Invalid property "node"
12 verbose stack
at checkDevEngines (/Users/yyy/.nvm/versions/node/v22.22.0/lib/node_modules/npm/node_modules/npm-install-checks/lib/dev-engines.js:100:13)
12 verbose stack
at Install.checkDevEngines (/Users/yyy/.nvm/versions/node/v22.22.0/lib/node_modules/npm/lib/base-cmd.js: 153:22)
12 verbose stack
12 verbose stack
12 verbose stack
at async #exec (/Users/yyy/.nvm/versions/node/v22.22.0/lib/node_modules/npm/lib/npm.js:251:7) at async Npm.exec (/Users/yyy/.nvm/versions/node/v22.22.0/lib/node_modules/npm/lib/npm.js:207:9)
at async module.exports (/Users/yyy/.nvm/versions/node/v22.22.0/lib/node_modules/npm/lib/cli/entry.js:74:5)
13 error Invalid property "node"
14 verbose cwd /Users/yyy/Documents/Code/git/bluebubbles-server
15 verbose os Darwin 25.3.0
16 verbose node v22.22.0
17 verbose npm v10.9.4
18 verbose exit 1
19 verbose code 1
For A complete log of this run can be found in: /Users/yyy/.npm/_10gs/2026-02-19T05_11_07_649Z-debug-0.1og
yyy@xxx bluebubbles-server
```
